version: '3.8'

services:
  postgis:
    image: postgis/postgis:latest
    container_name: map_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mapdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: map_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
>>>>>>> 9b0f6408c3ef6819bbdb61e80a70bf6de6fffc2b
  redis_data: